version: '3.8'
services:
  app:
    build: ./app
    ports:
      - 5000:5000
    volumes:
      - "./app:/app"
    links:
      - postgres
    environment:
      - SQLALCHEMY_URL=postgresql://postgres:postgres@postgres:5432/cleaning_robot
  test_app:
    build:
      context: ./app
      dockerfile: Dockerfile.test
    links:
      - postgres
    environment:
      - SQLALCHEMY_URL=postgresql://postgres:postgres@postgres:5432/cleaning_robot_test
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres:
    driver: local